### ISSUE TITLE
Closing this repo

### ISSUE THREAD

**Issue by AesteroidBlues** [awthomps/cse141l#1]
Does anyone care if I close this repo? If no one responds by Monday 3/9 I'll just do it :smile:

**Comment by AesteroidBlues** [comment]
cc @awthomps  @quesadilla  @ayke2014

**Comment by quesadilla** [comment]
I'm fine with closing the repo~

**Comment by awthomps** [comment]
So I wanted to save it so I forked it. Does that mean It will be safe when you close your repo?

**Comment by AesteroidBlues** [comment]
Yup it should be safe, I'll go ahead and close it since you made a fork!
Thanks :)

**Comment by awthomps** [comment]
No problem! Thanks for the heads up!

**Comment by AesteroidBlues** [comment]
Wait nevermind it will automatically delete the fork... weird behavior.
I'll just transfer ownership to you, Andrei

**Comment by AesteroidBlues** [comment]
My bad, you need to delete your fork @awthomps before I can transfer it to you :)

**Comment by awthomps** [comment]
Sorry, just saw this. Ill do it now
